language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

gemfile:
 - Gemfile

branches:
  only:
    - master
    - fix-lzop

before_install:
  - apt-get install -y lzop
  - gem update bundler
script: bundle exec rake test

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
